streaming_services:
- id: netflix
  name: Netflix
  enabled: true
- id: crave
  name: Crave
  enabled: true
- id: disney_plus
  name: Disney+
  enabled: true
- id: amazon_prime
  name: Amazon Prime Video
  enabled: true
- id: apple_tv
  name: Apple TV+
  enabled: true
- id: paramount_plus
  name: Paramount+
  enabled: false
- id: cbc_gem
  name: CBC Gem
  enabled: true
